name: GitHub CI
on:
  push:
    tags:
      - 'v*'
jobs:
  build_on_intel:
    runs-on: macOS-10.15
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 14.x
        uses: actions/setup-node@master
        with:
          node-version: 14.x
      - name: Install
        run: yarn install --frozen-lockfile --ignore-optional
      - name: Build
        run: yarn build:prod
